modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ZsoltMolnarrr/Paladins/issues"
license = "All Rights Reserved"

[[mods]]
modId = "paladins"
version = "${version}"
displayName = "Paladins & Priests (RPG Series)"
authors = "Daedelus"
description = '''
Protect and heal your friends as a Paladin or a Priest.
'''
logoFile = "icon.png"

[[dependencies.paladins]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.paladins]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_compat_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.paladins]]
modId = "azurelibarmor"
type = "required"
versionRange = "[${azure_lib_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.paladins]]
modId = "spell_engine"
type = "required"
versionRange = "[${spell_engine_version},)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.paladins]]
modId = "runes"
type = "required"
versionRange = "[${runes_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "paladins.mixins.json"
